// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzxexKxkUlmTFSd2Y2IFhJdb2S5lMK5S8',
    appId: '1:259251479203:web:5f19f0de49bf0eefcdd516',
    messagingSenderId: '259251479203',
    projectId: 'cloudvault-2c59d',
    authDomain: 'cloudvault-2c59d.firebaseapp.com',
    storageBucket: 'cloudvault-2c59d.firebasestorage.app',
    measurementId: 'G-XR1FGM62KX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO617v9bXGHmYSJWoGSDH-Itct_O21dxw',
    appId: '1:259251479203:android:4f76294d4473e21ccdd516',
    messagingSenderId: '259251479203',
    projectId: 'cloudvault-2c59d',
    storageBucket: 'cloudvault-2c59d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrYg3RDtIXna51_iLpuynUvfHEJW8rIBU',
    appId: '1:259251479203:ios:f11a37b09be96322cdd516',
    messagingSenderId: '259251479203',
    projectId: 'cloudvault-2c59d',
    storageBucket: 'cloudvault-2c59d.firebasestorage.app',
    iosBundleId: 'com.example.cloudvault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrYg3RDtIXna51_iLpuynUvfHEJW8rIBU',
    appId: '1:259251479203:ios:f11a37b09be96322cdd516',
    messagingSenderId: '259251479203',
    projectId: 'cloudvault-2c59d',
    storageBucket: 'cloudvault-2c59d.firebasestorage.app',
    iosBundleId: 'com.example.cloudvault',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzxexKxkUlmTFSd2Y2IFhJdb2S5lMK5S8',
    appId: '1:259251479203:web:fb5ea23e0c41d905cdd516',
    messagingSenderId: '259251479203',
    projectId: 'cloudvault-2c59d',
    authDomain: 'cloudvault-2c59d.firebaseapp.com',
    storageBucket: 'cloudvault-2c59d.firebasestorage.app',
    measurementId: 'G-B4TP2HMZMQ',
  );
}
